<?php
declare(strict_types=1);

/**
 * One-click production installer for Plesk / Hostatom.
 * Open once: https://your-domain/install.php
 * DELETE this file immediately after a successful install.
 */

$root = __DIR__;
$lockFile = $root . '/storage/install.lock';
$envFile = $root . '/.env';
$schemaFile = $root . '/database/schema.sql';

function h(string $s): string
{
    return htmlspecialchars($s, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

function alreadyInstalled(string $lockFile): bool
{
    return is_file($lockFile);
}

function writeEnvFile(string $path, array $data): void
{
    $lines = [
        '# Generated by install.php — do not commit',
        'APP_URL=',
        'DB_HOST=' . ($data['DB_HOST'] ?? 'localhost'),
        'DB_NAME=' . ($data['DB_NAME'] ?? ''),
        'DB_USER=' . ($data['DB_USER'] ?? ''),
        'DB_PASS=' . ($data['DB_PASS'] ?? ''),
        'SMTP_PASS=',
        'LINE_NOTIFY_TOKEN=',
        'OMISE_SECRET_KEY=',
        '',
    ];
    if (file_put_contents($path, implode("\n", $lines)) === false) {
        throw new RuntimeException('เขียนไฟล์ .env ไม่ได้ — ตรวจสิทธิ์โฟลเดอร์ httpdocs');
    }
}

function pdoConnect(string $host, string $name, string $user, string $pass): PDO
{
    $dsn = 'mysql:host=' . $host . ';dbname=' . $name . ';charset=utf8mb4';
    $pdo = new PDO($dsn, $user, $pass, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES => false,
        PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci',
    ]);
    $pdo->exec('SET CHARACTER SET utf8mb4');
    return $pdo;
}

/** Split SQL file into executable statements (skips CREATE DATABASE / USE). */
function loadSchemaStatements(string $sql): array
{
    $sql = preg_replace('/^\s*CREATE\s+DATABASE\b.*?;/im', '', $sql) ?? $sql;
    $sql = preg_replace('/^\s*USE\s+\w+\s*;/im', '', $sql) ?? $sql;
    $sql = preg_replace('/^\s*SET\s+NAMES\b.*?;/im', '', $sql) ?? $sql;
    $sql = preg_replace('/^\s*SET\s+CHARACTER\s+SET\b.*?;/im', '', $sql) ?? $sql;

    $parts = preg_split('/;\s*\n/', $sql) ?: [];
    $out = [];
    foreach ($parts as $part) {
        $stmt = trim($part);
        if ($stmt === '' || str_starts_with($stmt, '--')) {
            continue;
        }
        // drop full-line comment blocks at top
        $stmt = preg_replace('/^--.*$/m', '', $stmt) ?? $stmt;
        $stmt = trim($stmt);
        if ($stmt !== '') {
            $out[] = $stmt;
        }
    }
    return $out;
}

function tableExists(PDO $pdo, string $table): bool
{
    $stmt = $pdo->prepare('SHOW TABLES LIKE ?');
    $stmt->execute([$table]);
    return (bool) $stmt->fetchColumn();
}

function ensureUploadsWritable(string $root): array
{
    $dirs = [
        $root . '/uploads',
        $root . '/uploads/payments',
        $root . '/uploads/courses',
        $root . '/uploads/announcements',
        $root . '/uploads/sessions',
        $root . '/uploads/quizzes',
        $root . '/storage',
        $root . '/storage/logs',
    ];
    $notes = [];
    foreach ($dirs as $dir) {
        if (!is_dir($dir) && !@mkdir($dir, 0755, true)) {
            $notes[] = 'สร้างโฟลเดอร์ไม่ได้: ' . $dir;
            continue;
        }
        if (!is_writable($dir)) {
            @chmod($dir, 0755);
            if (!is_writable($dir)) {
                $notes[] = 'เขียนไม่ได้: ' . $dir . ' (ตั้งสิทธิ์ใน File Manager)';
            }
        }
    }
    return $notes;
}

function seedLeonaCourses(PDO $pdo): int
{
    if (!tableExists($pdo, 'courses')) {
        return 0;
    }
    $hasType = false;
    try {
        $cols = $pdo->query("SHOW COLUMNS FROM courses LIKE 'course_type'")->fetchAll();
        $hasType = (bool) $cols;
    } catch (Throwable $e) {
        $hasType = false;
    }

    $courses = [
        ['m1-intensive-live', 'ติวเข้มสอบเข้า ม.1 (สด)', 'สังคมศึกษา · รอบสด', 'คอร์สติวเข้มสอบเข้า ม.1 เน้นแนวข้อสอบจริง', 'exam_prep', 'beginner', 4500, 20, 12, 'สอบเข้า ม.1|สด|เทคนิค', 1, 1, 'live'],
        ['m1-intensive-online', 'ติวเข้มสอบเข้า ม.1 (ออนไลน์)', 'สังคมศึกษา · ออนไลน์', 'คอร์สติวเข้มสอบเข้า ม.1 เรียนออนไลน์ ทบทวนได้ตลอด', 'exam_prep', 'beginner', 3900, 20, 12, 'สอบเข้า ม.1|ออนไลน์|ทบทวน', 1, 2, 'recorded'],
        ['m4-intensive-live', 'ติวเข้มสอบเข้า ม.4 (สด)', 'สังคมศึกษา · รอบสด', 'คอร์สติวเข้มสอบเข้า ม.4 ครอบคลุมประวัติศาสตร์ ภูมิศาสตร์ หน้าที่พลเมือง', 'exam_prep', 'intermediate', 5500, 28, 16, 'สอบเข้า ม.4|สด|ครบวิชา', 1, 3, 'live'],
        ['m4-intensive-online', 'ติวเข้มสอบเข้า ม.4 (ออนไลน์)', 'สังคมศึกษา · ออนไลน์', 'คอร์สติวเข้มสอบเข้า ม.4 เรียนออนไลน์ เข้าถึงได้ 1 ปี', 'exam_prep', 'intermediate', 4900, 28, 16, 'สอบเข้า ม.4|ออนไลน์|1 ปี', 1, 4, 'recorded'],
        ['a-level-live', 'ติว A-Level สังคมศึกษา (สด)', 'เตรียมสอบ A-Level', 'ติวเข้ม A-Level สังคมศึกษา โฟกัสข้อสอบจริง', 'exam_prep', 'advanced', 6500, 30, 18, 'A-Level|สด|ข้อสอบจริง', 1, 5, 'live'],
        ['a-level-online', 'ติว A-Level สังคมศึกษา (ออนไลน์)', 'เตรียมสอบ A-Level', 'ติว A-Level ออนไลน์ ทบทวนได้ตามจังหวะตัวเอง', 'exam_prep', 'advanced', 5900, 30, 18, 'A-Level|ออนไลน์|ทบทวน', 1, 6, 'recorded'],
    ];

    $inserted = 0;
    foreach ($courses as $c) {
        $check = $pdo->prepare('SELECT id FROM courses WHERE slug = ? LIMIT 1');
        $check->execute([$c[0]]);
        if ($check->fetchColumn()) {
            continue;
        }
        if ($hasType) {
            $pdo->prepare('
                INSERT INTO courses
                    (slug, title, subtitle, description, category, level, price, duration_hours, lesson_count, highlights, is_featured, is_active, sort_order, course_type)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?, ?)
            ')->execute([$c[0], $c[1], $c[2], $c[3], $c[4], $c[5], $c[6], $c[7], $c[8], $c[9], $c[10], $c[11], $c[12]]);
        } else {
            $pdo->prepare('
                INSERT INTO courses
                    (slug, title, subtitle, description, category, level, price, duration_hours, lesson_count, highlights, is_featured, sort_order)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ')->execute([$c[0], $c[1], $c[2], $c[3], $c[4], $c[5], $c[6], $c[7], $c[8], $c[9], $c[10], $c[11]]);
        }
        $inserted++;
    }
    return $inserted;
}

$logs = [];
$errors = [];
$done = false;
$form = [
    'DB_HOST' => trim((string) ($_POST['DB_HOST'] ?? 'localhost')),
    'DB_NAME' => trim((string) ($_POST['DB_NAME'] ?? '')),
    'DB_USER' => trim((string) ($_POST['DB_USER'] ?? '')),
    'DB_PASS' => (string) ($_POST['DB_PASS'] ?? ''),
    'seed_exams' => !empty($_POST['seed_exams']),
    'seed_courses' => !isset($_POST['run']) || !empty($_POST['seed_courses']),
    'confirm' => !empty($_POST['confirm']),
];

if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['run'] ?? '') === '1') {
    try {
        if (alreadyInstalled($lockFile)) {
            throw new RuntimeException('ติดตั้งไปแล้ว (พบ storage/install.lock) — ลบไฟล์นั้นถ้าต้องการติดตั้งใหม่');
        }
        if (!$form['confirm']) {
            throw new RuntimeException('กรุณาติ๊กยืนยันก่อนติดตั้ง');
        }
        if ($form['DB_NAME'] === '' || $form['DB_USER'] === '') {
            throw new RuntimeException('กรอกชื่อฐานข้อมูลและชื่อผู้ใช้ให้ครบ');
        }
        if (!is_file($schemaFile)) {
            throw new RuntimeException('ไม่พบ database/schema.sql');
        }

        $logs[] = 'ทดสอบเชื่อมต่อ MySQL...';
        $pdo = pdoConnect($form['DB_HOST'], $form['DB_NAME'], $form['DB_USER'], $form['DB_PASS']);
        $logs[] = 'เชื่อมต่อสำเร็จ';

        $logs[] = 'เขียนไฟล์ .env...';
        writeEnvFile($envFile, $form);
        $logs[] = 'บันทึก .env แล้ว';

        $uploadNotes = ensureUploadsWritable($root);
        foreach ($uploadNotes as $n) {
            $logs[] = 'คำเตือน: ' . $n;
        }

        $fresh = !tableExists($pdo, 'admin_users');
        if ($fresh) {
            $logs[] = 'ติดตั้ง schema ใหม่...';
            $statements = loadSchemaStatements((string) file_get_contents($schemaFile));
            $ok = 0;
            $skip = 0;
            foreach ($statements as $sql) {
                // Skip legacy HSK course/lesson seed — replaced by Leona packs below
                if (preg_match('/^INSERT\s+INTO\s+courses\b/i', $sql) || preg_match('/^INSERT\s+INTO\s+lessons\b/i', $sql)) {
                    $skip++;
                    continue;
                }
                if (preg_match('/^INSERT\s+INTO\s+site_settings\b/i', $sql)) {
                    // brand defaults applied after migrations
                    $skip++;
                    continue;
                }
                try {
                    $pdo->exec($sql);
                    $ok++;
                } catch (Throwable $e) {
                    // allow re-run-ish inserts
                    if (str_contains($e->getMessage(), 'Duplicate')) {
                        $skip++;
                        continue;
                    }
                    throw new RuntimeException('SQL ล้มเหลว: ' . $e->getMessage() . "\n---\n" . substr($sql, 0, 200));
                }
            }
            $logs[] = "schema: รัน {$ok} คำสั่ง (ข้าม seed เก่า {$skip})";
        } else {
            $logs[] = 'พบตารางอยู่แล้ว — ข้าม schema หลัก ไปรัน migration';
        }

        // Bootstrap app config so migration scripts can use db()
        require_once $root . '/includes/database.php';

        // Verify connection constants match what we wrote
        if (DB_NAME !== $form['DB_NAME']) {
            throw new RuntimeException('ไฟล์ .env ยังไม่ถูกโหลดถูกต้อง — ลองรีเฟรชแล้วติดตั้งอีกครั้ง');
        }

        $migrationFiles = [
            $root . '/database/run_migration.php',
            $root . '/database/run_migration_phase2.php',
            $root . '/database/run_migration_phase3.php',
            $root . '/database/run_migration_phase4.php',
            $root . '/database/run_migration_phase5.php',
            $root . '/database/run_migration_phase6.php',
            $root . '/database/run_migration_phase7.php',
            $root . '/database/run_migration_phase8.php',
            $root . '/database/run_migration_phase9.php',
            $root . '/database/run_migration_phase10.php',
            $root . '/database/run_migration_phase11.php',
            $root . '/database/run_migration_phase12.php',
        ];

        foreach ($migrationFiles as $file) {
            $name = basename($file);
            if (!is_file($file)) {
                $logs[] = "ข้าม {$name} (ไม่พบไฟล์)";
                continue;
            }
            $logs[] = "รัน {$name}...";
            ob_start();
            try {
                // Migrations call header(); ignore once HTML/session already started.
                @include $file;
                $out = trim((string) ob_get_clean());
                if ($out !== '') {
                    $logs[] = $name . ': ' . str_replace("\n", ' | ', $out);
                }
            } catch (Throwable $e) {
                ob_end_clean();
                $logs[] = "{$name}: " . $e->getMessage();
            }
        }

        // Leona brand settings
        require_once $root . '/includes/site_content.php';
        $brand = 'กวดวิชาเดอะลีโอน่า';
        $tagline = 'ติวสังคมศึกษา ประวัติศาสตร์ · สอบเข้า ม.1 ม.4 และ A-Level';
        saveSetting('site_title', $brand);
        saveSetting('site_tagline', $tagline);
        saveSetting('site_url', 'https://www.theleonatutors.com');
        saveSetting('phone', '082-8672627');
        saveSetting('email_from_name', $brand);
        $logs[] = 'ตั้งค่าแบรนด์ Leona แล้ว';

        if ($form['seed_courses']) {
            $n = seedLeonaCourses(db());
            $logs[] = "ใส่คอร์สตัวอย่าง Leona {$n} คอร์ส";
        }

        if ($form['seed_exams']) {
            require_once $root . '/includes/exam.php';
            if (examTablesReady()) {
                ob_start();
                try {
                    @include $root . '/storage/seed_exam_packs.php';
                    $out = trim((string) ob_get_clean());
                    $logs[] = 'seed ข้อสอบ: ' . ($out !== '' ? str_replace("\n", ' | ', $out) : 'เสร็จ');
                } catch (Throwable $e) {
                    ob_end_clean();
                    $logs[] = 'seed ข้อสอบ: ' . $e->getMessage();
                }
            } else {
                $logs[] = 'ข้าม seed ข้อสอบ — ตาราง exam ยังไม่พร้อม';
            }
        }

        if (!is_dir(dirname($lockFile))) {
            @mkdir(dirname($lockFile), 0755, true);
        }
        file_put_contents($lockFile, date('c') . " installed\n");
        $done = true;
        $logs[] = 'สร้าง storage/install.lock แล้ว';
        $logs[] = 'สำเร็จ — ลบไฟล์ install.php ทันที';
    } catch (Throwable $e) {
        $errors[] = $e->getMessage();
    }
}

$locked = alreadyInstalled($lockFile);
header('Content-Type: text/html; charset=UTF-8');
?>
<!DOCTYPE html>
<html lang="th">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ติดตั้ง THE LEONA TUTORS LMS</title>
    <style>
        :root { --bg:#f4f1ea; --card:#fff; --ink:#1e3f3a; --accent:#c45c26; --line:#d9d2c5; --ok:#166534; --err:#991b1b; }
        * { box-sizing: border-box; }
        body { margin:0; font-family: Georgia, "Times New Roman", serif; background:linear-gradient(160deg,#eef3f1,#f7f2e8 45%,#f0e6d8); color:var(--ink); min-height:100vh; }
        .wrap { max-width:640px; margin:0 auto; padding:2rem 1.25rem 3rem; }
        h1 { font-size:1.6rem; margin:0 0 .35rem; }
        .sub { opacity:.8; margin:0 0 1.5rem; line-height:1.5; }
        .card { background:var(--card); border:1px solid var(--line); border-radius:14px; padding:1.25rem 1.35rem; box-shadow:0 10px 30px rgba(30,63,58,.06); }
        label { display:block; font-size:.92rem; margin:0 0 .35rem; }
        input[type=text], input[type=password] { width:100%; padding:.7rem .8rem; border:1px solid var(--line); border-radius:8px; font:inherit; margin-bottom:.9rem; }
        .row { display:flex; gap:.75rem; }
        .row > * { flex:1; }
        .check { display:flex; gap:.55rem; align-items:flex-start; margin:.55rem 0; font-size:.95rem; }
        .check input { margin-top:.2rem; }
        button { appearance:none; border:0; background:var(--ink); color:#fff; padding:.85rem 1.2rem; border-radius:999px; font:inherit; cursor:pointer; width:100%; margin-top:.75rem; }
        button:hover { background:#16332f; }
        .log { margin-top:1rem; background:#102623; color:#d7efe8; border-radius:10px; padding:1rem; font-family:ui-monospace,Consolas,monospace; font-size:.82rem; white-space:pre-wrap; max-height:320px; overflow:auto; }
        .ok { color:var(--ok); font-weight:700; margin:0 0 .75rem; }
        .err { color:var(--err); background:#fef2f2; border:1px solid #fecaca; padding:.75rem .9rem; border-radius:8px; margin:0 0 1rem; white-space:pre-wrap; }
        .warn { background:#fff7ed; border:1px solid #fed7aa; padding:.75rem .9rem; border-radius:8px; margin:0 0 1rem; font-size:.95rem; }
        a { color:var(--accent); }
        .done-actions { display:grid; gap:.5rem; margin-top:1rem; }
        .done-actions a { display:block; text-align:center; padding:.75rem; border-radius:999px; text-decoration:none; border:1px solid var(--line); color:var(--ink); background:#fff; }
        .done-actions a.primary { background:var(--ink); color:#fff; border-color:var(--ink); }
    </style>
</head>
<body>
<div class="wrap">
    <h1>ติดตั้ง THE LEONA TUTORS</h1>
    <p class="sub">ตัวช่วยติดตั้งฐานข้อมูลครั้งเดียวบน Plesk — กรอกค่า DB ที่สร้างไว้ แล้วกดติดตั้ง</p>

    <?php if ($locked && !$done): ?>
        <div class="card">
            <p class="ok">ติดตั้งไปแล้ว</p>
            <p>พบไฟล์ <code>storage/install.lock</code> — ถ้าเว็บพร้อมใช้งานแล้ว ให้<strong>ลบไฟล์ install.php</strong> ออกจากเซิร์ฟเวอร์ทันที</p>
            <div class="done-actions">
                <a class="primary" href="/public/">เปิดหน้าเว็บ</a>
                <a href="/public/admin-login.php">เข้า Admin</a>
            </div>
        </div>
    <?php elseif ($done): ?>
        <div class="card">
            <p class="ok">ติดตั้งสำเร็จ</p>
            <div class="warn">
                <strong>ทำทันที:</strong>
                <ol>
                    <li>ลบไฟล์ <code>install.php</code> ออกจากเซิร์ฟเวอร์</li>
                    <li>เข้า Admin แล้วเปลี่ยนรหัสผ่าน <code>admin / admin123</code></li>
                </ol>
            </div>
            <div class="done-actions">
                <a class="primary" href="/public/">เปิดหน้าเว็บ</a>
                <a href="/public/courses.php">ดูคอร์ส</a>
                <a href="/public/exams.php">จำลองสนามสอบ</a>
                <a href="/public/admin-login.php">เข้า Admin (admin / admin123)</a>
            </div>
            <?php if ($logs): ?>
                <div class="log"><?= h(implode("\n", $logs)) ?></div>
            <?php endif; ?>
        </div>
    <?php else: ?>
        <div class="card">
            <div class="warn">
                ก่อนหน้านี้ให้สร้าง Database + User ใน Plesk ไว้ก่อน แล้วเอามากรอกด้านล่าง
            </div>

            <?php foreach ($errors as $err): ?>
                <div class="err"><?= h($err) ?></div>
            <?php endforeach; ?>

            <form method="post" autocomplete="off">
                <input type="hidden" name="run" value="1">
                <div class="row">
                    <div>
                        <label for="DB_HOST">DB Host</label>
                        <input id="DB_HOST" name="DB_HOST" type="text" value="<?= h($form['DB_HOST']) ?>" required>
                    </div>
                    <div>
                        <label for="DB_NAME">DB Name</label>
                        <input id="DB_NAME" name="DB_NAME" type="text" value="<?= h($form['DB_NAME']) ?>" required placeholder="เช่น leona_lms">
                    </div>
                </div>
                <label for="DB_USER">DB User</label>
                <input id="DB_USER" name="DB_USER" type="text" value="<?= h($form['DB_USER']) ?>" required>
                <label for="DB_PASS">DB Password</label>
                <input id="DB_PASS" name="DB_PASS" type="password" value="<?= h($form['DB_PASS']) ?>">

                <label class="check"><input type="checkbox" name="seed_courses" value="1" <?= $form['seed_courses'] ? 'checked' : '' ?>> ใส่คอร์สตัวอย่าง Leona 6 คอร์ส</label>
                <label class="check"><input type="checkbox" name="seed_exams" value="1" <?= $form['seed_exams'] || !isset($_POST['run']) ? 'checked' : '' ?>> ใส่ชุดจำลองสนามสอบตัวอย่าง</label>
                <label class="check"><input type="checkbox" name="confirm" value="1" required> ยืนยันติดตั้งลงฐานข้อมูลนี้</label>

                <button type="submit">เริ่มติดตั้ง</button>
            </form>

            <?php if ($logs): ?>
                <div class="log"><?= h(implode("\n", $logs)) ?></div>
            <?php endif; ?>
        </div>
    <?php endif; ?>
</div>
</body>
</html>
